"""empty message

Revision ID: 634fdf65d4d7
Revises: d238c6b359e5
Create Date: 2025-01-05 18:25:27.440585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634fdf65d4d7'
down_revision = 'd238c6b359e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
